export const constants = {
    SINGUP_REQUEST: "SIGNUP_REQUEST",
    SIGNUP_SUCCESS : "SIGNUP_SUCCESS",
    SIGNUP_FAIL : "SIGNUP_FAIL",
    
    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_SUCCESS : "LOGIN_SUCCESS",
    LOGIN_FAIL : "LOGIN_FAIL",

    LOGOUT : "LOGOUT",
}


